/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNastaveniaRouteImport } from './routes/_authenticated/nastavenia'
import { Route as AuthenticatedNovaPlatbaRouteImport } from './routes/_authenticated/nova-platba'
import { Route as AuthenticatedPlatbyRouteImport } from './routes/_authenticated/platby'
import { Route as AuthenticatedPrijatRouteImport } from './routes/_authenticated/prijat'
import { Route as AuthenticatedRozpocetRouteImport } from './routes/_authenticated/rozpocet'
import { Route as AuthenticatedSporenieRouteImport } from './routes/_authenticated/sporenie'
import { Route as AuthenticatedTransakciaIdRouteImport } from './routes/_authenticated/transakcia.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNastaveniaRoute = AuthenticatedNastaveniaRouteImport.update({
  id: '/_authenticated/nastavenia',
  path: '/nastavenia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovaPlatbaRoute = AuthenticatedNovaPlatbaRouteImport.update({
  id: '/_authenticated/nova-platba',
  path: '/nova-platba',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatbyRoute = AuthenticatedPlatbyRouteImport.update({
  id: '/_authenticated/platby',
  path: '/platby',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrijatRoute = AuthenticatedPrijatRouteImport.update({
  id: '/_authenticated/prijat',
  path: '/prijat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRozpocetRoute = AuthenticatedRozpocetRouteImport.update({
  id: '/_authenticated/rozpocet',
  path: '/rozpocet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSporenieRoute = AuthenticatedSporenieRouteImport.update({
  id: '/_authenticated/sporenie',
  path: '/sporenie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransakciaIdRoute =
  AuthenticatedTransakciaIdRouteImport.update({
    id: '/_authenticated/transakcia/$id',
    path: '/transakcia/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/nastavenia': typeof AuthenticatedNastaveniaRoute
  '/nova-platba': typeof AuthenticatedNovaPlatbaRoute
  '/platby': typeof AuthenticatedPlatbyRoute
  '/prijat': typeof AuthenticatedPrijatRoute
  '/rozpocet': typeof AuthenticatedRozpocetRoute
  '/sporenie': typeof AuthenticatedSporenieRoute
  '/': typeof AuthenticatedIndexRoute
  '/transakcia/$id': typeof AuthenticatedTransakciaIdRoute
}
export interface FileRoutesByTo {
  '/nastavenia': typeof AuthenticatedNastaveniaRoute
  '/nova-platba': typeof AuthenticatedNovaPlatbaRoute
  '/platby': typeof AuthenticatedPlatbyRoute
  '/prijat': typeof AuthenticatedPrijatRoute
  '/rozpocet': typeof AuthenticatedRozpocetRoute
  '/sporenie': typeof AuthenticatedSporenieRoute
  '/': typeof AuthenticatedIndexRoute
  '/transakcia/$id': typeof AuthenticatedTransakciaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/nastavenia': typeof AuthenticatedNastaveniaRoute
  '/_authenticated/nova-platba': typeof AuthenticatedNovaPlatbaRoute
  '/_authenticated/platby': typeof AuthenticatedPlatbyRoute
  '/_authenticated/prijat': typeof AuthenticatedPrijatRoute
  '/_authenticated/rozpocet': typeof AuthenticatedRozpocetRoute
  '/_authenticated/sporenie': typeof AuthenticatedSporenieRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/transakcia/$id': typeof AuthenticatedTransakciaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/nastavenia'
    | '/nova-platba'
    | '/platby'
    | '/prijat'
    | '/rozpocet'
    | '/sporenie'
    | '/'
    | '/transakcia/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/nastavenia'
    | '/nova-platba'
    | '/platby'
    | '/prijat'
    | '/rozpocet'
    | '/sporenie'
    | '/'
    | '/transakcia/$id'
  id:
    | '__root__'
    | '/_authenticated/nastavenia'
    | '/_authenticated/nova-platba'
    | '/_authenticated/platby'
    | '/_authenticated/prijat'
    | '/_authenticated/rozpocet'
    | '/_authenticated/sporenie'
    | '/_authenticated/'
    | '/_authenticated/transakcia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedNastaveniaRoute: typeof AuthenticatedNastaveniaRoute
  AuthenticatedNovaPlatbaRoute: typeof AuthenticatedNovaPlatbaRoute
  AuthenticatedPlatbyRoute: typeof AuthenticatedPlatbyRoute
  AuthenticatedPrijatRoute: typeof AuthenticatedPrijatRoute
  AuthenticatedRozpocetRoute: typeof AuthenticatedRozpocetRoute
  AuthenticatedSporenieRoute: typeof AuthenticatedSporenieRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTransakciaIdRoute: typeof AuthenticatedTransakciaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nastavenia': {
      id: '/_authenticated/nastavenia'
      path: '/nastavenia'
      fullPath: '/nastavenia'
      preLoaderRoute: typeof AuthenticatedNastaveniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova-platba': {
      id: '/_authenticated/nova-platba'
      path: '/nova-platba'
      fullPath: '/nova-platba'
      preLoaderRoute: typeof AuthenticatedNovaPlatbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platby': {
      id: '/_authenticated/platby'
      path: '/platby'
      fullPath: '/platby'
      preLoaderRoute: typeof AuthenticatedPlatbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prijat': {
      id: '/_authenticated/prijat'
      path: '/prijat'
      fullPath: '/prijat'
      preLoaderRoute: typeof AuthenticatedPrijatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rozpocet': {
      id: '/_authenticated/rozpocet'
      path: '/rozpocet'
      fullPath: '/rozpocet'
      preLoaderRoute: typeof AuthenticatedRozpocetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sporenie': {
      id: '/_authenticated/sporenie'
      path: '/sporenie'
      fullPath: '/sporenie'
      preLoaderRoute: typeof AuthenticatedSporenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transakcia/$id': {
      id: '/_authenticated/transakcia/$id'
      path: '/transakcia/$id'
      fullPath: '/transakcia/$id'
      preLoaderRoute: typeof AuthenticatedTransakciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedNastaveniaRoute: AuthenticatedNastaveniaRoute,
  AuthenticatedNovaPlatbaRoute: AuthenticatedNovaPlatbaRoute,
  AuthenticatedPlatbyRoute: AuthenticatedPlatbyRoute,
  AuthenticatedPrijatRoute: AuthenticatedPrijatRoute,
  AuthenticatedRozpocetRoute: AuthenticatedRozpocetRoute,
  AuthenticatedSporenieRoute: AuthenticatedSporenieRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTransakciaIdRoute: AuthenticatedTransakciaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
